version: '3.7'
services:
        reddit:
                build:
                        context: ./reddit
                        network: host
                volumes:
                        - .:/reddit
                network_mode: host
                environment:
                        REDIS_HOST: '0.0.0.0'
                        REDIS_PORT: '6379'
                depends_on:
                        - redis
        redis:
                image: redis
                ports: 
                        - '6379:6379'

