version: '3.7'
services:
        reddit:
                build: ./reddit
                environment:
                        REDIS_HOST: 'redis'
                        REDIS_PORT: '6379'
                depends_on:
                        - redis
        leaderboard:
                build: ./leaderboard
                environment:
                        REDIS_HOST: 'redis'
                        REDIS_PORT: '6379'
                depends_on:
                        - redis
                ports: 
                        - '5000:5000'
        redis:
                image: redis
                ports: 
                        - '6379:6379'

